snf_scheduler/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('tokens/', views.get_tokens, name='tokens'),
]

snf_scheduler/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('home/', views.home, name='home'),

    path('snf/list', views.list_snfs, name='list_snfs'),
    path('snf/delete/', views.delete_snf, name='delete_snf'),
    path('snf/add/', views.add_snf, name='add_snf'),
    path('snf/<int:pk>/', views.get_snf, name='get_snf'),
    path('snf/edit/<int:pk>/', views.edit_snf, name='edit_snf'),

    path('patient/list', views.list_patients, name='list_patients'),
    path('patient/delete/', views.delete_patient, name='delete_patient'),
    path('patient/add/', views.add_patient, name='add_patient'),
    path('patient/<int:pk>/', views.get_patient, name='get_patient'),
    path('patient/edit/<int:pk>/', views.edit_patient, name='edit_patient'),
]

snf_scheduler/scheduler/urls.py
from django.urls import path
from . import views

app_name = 'scheduler'

urlpatterns = [
    path('', views.api_root, name='api-root'),
    path('snfs/', views.SNFListCreate.as_view(), name='snf-list-create'),
    path('snfs/<int:pk>/', views.SNFDetail.as_view(), name='snf-detail'),
    path('patients/', views.PatientListCreate.as_view(), name='patient-list-create'),
    path('patients/<int:pk>/', views.PatientDetail.as_view(), name='patient-detail'),
    path('appointments/', views.AppointmentListCreate.as_view(), name='appointment-list-create'),
    path('appointments/<int:pk>/', views.AppointmentDetail.as_view(), name='appointment-detail'),
    path('appointment-notes/', views.AppointmentNoteListCreate.as_view(), name='appointment-notes-list-create'),
    path('appointment-notes/<int:pk>/', views.AppointmentNoteDetail.as_view(), name='appointments-note-detail'),
    path('patient-notes/', views.PatientNoteListCreate.as_view(), name='patient-notes-list-create'),
    path('patient-notes/<int:pk>/', views.PatientNoteDetail.as_view(), name='patient-notes-detail'),
]

snf_scheduler/snf_scheduler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('api/scheduler/', include('scheduler.urls')),
]

snf_scheduler/main/models.py
from django.db import models

# Create your models here.

snf_scheduler/main/forms.py
from django import forms
from scheduler.models import SNF, Patient, Appointment, AppointmentNote, PatientNote

class SNFForm(forms.ModelForm):
    class Meta:
        model = SNF
        fields = ['id', 'name', 'description', 'address', 'phone', 'hour_opens', 'hour_closes', 'max_concurrent_appointments']
        widgets = {
            'id': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'autofocus': 'autofocus'}),  # Set focus to this field
            'description': forms.Textarea(attrs={'rows': 3}),  # Adjust rows as needed
            'address': forms.Textarea(attrs={'rows': 2}),
            'hour_opens': forms.TimeInput(attrs={'type': 'time'}),
            'hour_closes': forms.TimeInput(attrs={'type': 'time'}),
        }
        labels = {
            'name': 'Facility Name',  # More descriptive label
            'max_concurrent_appointments': 'Max Appointments',  # More concise label
        }
        help_texts = {
            'phone': 'Enter phone number in format XXX-XXX-XXXX',
            'hour_opens': '12 hour format',
            'hour_closes': '12 hour format',
        }
        error_messages = {
            'name': {
                'required': "Facility Name is required.",
            },
            'address': {
                'required': "Address is required.",
            },
            'phone': {
                'required': "Phone number is required.",
                'invalid': "Enter a valid phone number.",
            },
            'hour_opens': {
                'required': "Opening hour is required.",
                'invalid': "Enter a valid time for the opening hour.",
            },
            'hour_closes': {
                'required': "Closing hour is required.",
                'invalid': "Enter a valid time for the closing hour.",
            },
            'max_concurrent_appointments': {
                'invalid': "Please enter a valid number",
                'required': "Max Appointments is required",
            },
        }

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        # Basic phone number validation (you can use a more robust regex)
        if phone and len(phone) != 12 or not all(c.isdigit() or c == '-' for c in phone) or phone[3] != '-' or phone[7] != '-':
            raise forms.ValidationError("Invalid phone number format. Use XXX-XXX-XXXX")
        return phone

    def clean(self):
        cleaned_data = super().clean()
        hour_opens = cleaned_data.get('hour_opens')
        hour_closes = cleaned_data.get('hour_closes')

        if hour_opens and hour_closes and hour_opens >= hour_closes:
            raise forms.ValidationError("Opening time must be before closing time.")

        return cleaned_data


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['id', 'first_name', 'last_name', 'date_of_birth', 'active']
        widgets = {
            'id': forms.HiddenInput(),
            'first_name': forms.TextInput(attrs={'autofocus': 'autofocus'}),  # Set focus to this field
            'last_name': forms.TextInput(),
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'active': forms.CheckboxInput(),
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
        }
        help_texts = {
            'phone': 'Enter phone number in format XXX-XXX-XXXX',
            'date_of_birth': 'Date of birth',
        }
        error_messages = {
            'first_name': {
                'required': "First Name is required.",
            },
            'last_name': {
                'required': "Last Name is required.",
            },
            'date_of_birth': {
                'required': "Date of birth is required.",
                'invalid': "Enter a valid date.",
            }
        }

snf_scheduler/main/views.py
from django.shortcuts import render
from scheduler.models import SNF, Patient, Appointment, AppointmentNote, PatientNote
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
import json
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SNFForm, PatientForm


# Create your views here.
@login_required
def home(request):
    context = {}
    return render(request, 'main/home.html', context)

#################
### SNF Views ###
#################
@login_required
@require_http_methods(["GET"])
def list_snfs(request):
    snfs = SNF.objects.all()

    # Handle AJAX request
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        try:
            # Create data set to return
            data = list(snfs.values('id', 'name', 'address', 'description', 'phone', 'hour_opens', 'hour_closes', 'max_concurrent_appointments' ))

            for snf in data:
                snf['hour_opens'] = str(snf['hour_opens'])
                snf['hour_closes'] = str(snf['hour_closes'])

            return JsonResponse({
                'success': True,
                'data': data
            })
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)
    # If not AJAX, render the template
    else:
        context = {}
        context['snfs'] = snfs
        return render(request, 'main/snf.html', context)


@login_required
@require_http_methods(["GET"])
def get_snf(request):
    if request.GET.get('snf_id'):
        snf_id = request.GET.get('snf_id')
        try:
            snf = SNF.objects.get(id=snf_id)
            return JsonResponse({
                'success': True,
                'data': {
                    'id': snf.id,
                    'name': snf.name,
                    'address': snf.address,
                    'phone': snf.phone,
                    'hour_opens': str(snf.hour_opens),  # Convert time to string
                    'hour_closes': str(snf.hour_closes),  # Convert time to string
                    'max_concurrent_appointments': snf.max_concurrent_appointments
                }
            })
        except SNF.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'SNF not found.'}, status=404)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)


@login_required
def add_snf(request):
    if request.method == 'GET':
        form = SNFForm()
        return render(request, 'main/add_snf.html', {'form': form})

    if request.method == 'POST':
        form = SNFForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        return render(request, 'main/add_snf.html', {'form': form})

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=400)


@login_required
def edit_snf(request, pk):
    if request.method == 'GET':
        snf = SNF.objects.get(pk=pk)
        form = SNFForm(instance=snf)
        return render(request, 'main/edit_snf.html', {'form': form})

    if request.method == 'POST':
        snf = SNF.objects.get(pk=pk)
        form = SNFForm(request.POST, instance=snf)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        return render(request, 'main/edit_snf.html', {'form': form})

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=400)


@login_required
@require_http_methods(["DELETE"])
def delete_snf(request):
    if request.method == 'DELETE':
        # Since we are sending data in the body of a DELETE request, we will
        # use request.body to get the data instead of request.DELETE
        data = json.loads(request.body)
        snf_id = data.get('snf_id')

        if not snf_id:
            return JsonResponse({'success': False, 'error': 'SNF ID is required.'}, status=400)

        try:
            snf = SNF.objects.get(id=snf_id)
            snf.delete()
            return JsonResponse({'success': True})
        except SNF.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'SNF not found.'}, status=404)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)



#####################
### Patient Views ###
#####################
@login_required
@require_http_methods(["GET"])
def list_patients(request):
    patients = Patient.objects.all()

    # Handle AJAX request
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        try:
            data = []
            # We are looping through the patients and creating a dictionary for each patient, because
            # we cannot directly serialize the queryset to JSON using list(patients.values()) or patients.values()
            # This due to the Patient model having two computed fields:  `age` and `name`
            # Properties defined on the model are not included by default.
            for patient in patients:
                data.append({
                    'id': patient.id,
                    'name': patient.name, # Directly using the name property from the model
                    'first_name': patient.first_name,
                    'last_name': patient.last_name,
                    'date_of_birth': patient.date_of_birth,
                    'age': patient.age,  # Directly using the age property from the model
                    'date_of_last_appointment': patient.date_of_last_appointment,
                    'date_of_next_appointment': patient.date_of_next_appointment,
                    'active': patient.active
                })

            return JsonResponse({
                'success': True,
                'data': data
            })
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)
    # If not AJAX, render the template
    else:
        context = {'patients': patients}
        return render(request, 'main/patient.html', context)


@login_required
def add_patient(request):
    if request.method == 'GET':
        form = PatientForm()
        return render(request, 'main/add_patient.html', {'form': form})

    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True, 'message': 'Patient added successfully.'})
        else:
            print("Inside add_patient::POST::is_valid::else")
            print(form.errors)
        return render(request, 'main/add_patient.html', {'form': form})

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=400)


@login_required
def delete_patient(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        patient_id = data.get('patient_id')

        if not patient_id:
            return JsonResponse({'success': False, 'error': '{Patient} ID is required.'}, status=400)

        try:
            patient = Patient.objects.get(id=patient_id)
            message = f'Patient {patient.name} (ID: {patient_id}) deleted successfully.'
            patient.delete()
            return JsonResponse({'success': True, 'message': message})
        except Patient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Patient not found.'}, status=404)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)


@login_required
@require_http_methods(["GET"])
def get_patient(request):
    if request.GET.get('patient_id'):
        patient_id = request.GET.get('patient_id')
        try:
            patient = Patient.objects.get(id=patient_id)
            return JsonResponse({
                'success': True,
                'data': {
                    'id': patient.id,
                    'first_name': patient.first_name,
                    'last_name': patient.last_name,
                    'date_of_birth': patient.date_of_birth,
                    'active': patient.active
                }
            })
        except Patient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Patient not found.'}, status=404)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)


@login_required
def edit_patient(request, pk):
    if request.method == 'GET':
        patient = Patient.objects.get(pk=pk)
        form = PatientForm(instance=patient)
        form.id = patient.id
        return render(request, 'main/edit_patient.html', {'form': form, 'patient': patient})

    if request.method == 'POST':
        patient = Patient.objects.get(pk=pk)
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        return render(request, 'main/edit_patient.html', {'form': form})

    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=400)

snf_scheduler/main/templates/main/add_patient.html
{% load widget_tweaks %}
<!-- Modal for Adding Patient -->
<div class="modal fade" id="addPatientModal" tabindex="-1" aria-labelledby="addPatientModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addPatientModalLabel">Add New Patient</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
                <div id="addModalBodyContent">

                    <div class="modal-body" id="addModalBodyContainer">
                        <form method="post" id="addPatientForm" novalidate>
                            {% csrf_token %}
                            {% if form.errors %}
                                <div class="alert alert-danger">
                                    <p>Please correct the errors below.</p>
                                </div>
                            {% endif %}

                            {{ form.non_field_errors }}  {# Errors not associated with a specific field #}

                            <div class="row g-3">
                                {% for field in form %}
                                    <div class="col-md-6 {% if field.errors %}has-error{% endif %}">
                                        <label for="{{ field.id_for_label }}"
                                               class="form-label {% if field.errors %}text-danger{% endif %}">
                                                    {{ field.label }}
                                        </label></br>
                                        {% if field.errors %}
                                            {{ field|add_class:"form-control is-invalid" }}
                                        {% else %}
                                            {{ field|add_class:"form-control" }}
                                        {% endif %}
                                        {% if field.errors %}
                                            <div class="invalid-feedback">
                                                {{ field.errors }}
                                            </div>
                                        {% endif %}
                                        {% if field.help_text %}
                                            <div id="{{ field.id_for_label }}Help" class="form-text">{{ field.help_text }}</div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                        </form>
                    </div>

                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="cancelPatientBtn">Cancel</button>
                <button type="button" form="addPatientForm" class="btn btn-primary" id="addPatientBtn">Add Patient</button>
            </div>
        </div>
    </div>
</div>

snf_scheduler/main/templates/main/add_snf.html
{% load widget_tweaks %}
<div class="modal-body" id="addModalBodyContainer">
    <form method="post" id="addSNFForm" novalidate>
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Please correct the errors below.</p>
            </div>
        {% endif %}

        {{ form.non_field_errors }}  {# Errors not associated with a specific field #}

        <div class="row g-3">
            {% for field in form %}
                <div class="col-md-6 {% if field.errors %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}"
                           class="form-label {% if field.errors %}text-danger{% endif %}">
                                {{ field.label }}
                    </label></br>
                    {% if field.errors %}
                        {{ field|add_class:"form-control is-invalid" }}
                    {% else %}
                        {{ field|add_class:"form-control" }}
                    {% endif %}
                    {% if field.errors %}
                        <div class="invalid-feedback">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                    {% if field.help_text %}
                        <div id="{{ field.id_for_label }}Help" class="form-text">{{ field.help_text }}</div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </form>
</div>

snf_scheduler/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SNF Scheduler{% endblock %}</title>

    <!-- Load all the static resources -->
    {% load static %}

    <!-- Bootstrap CSS and Icons -->
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_messages %}
    {% load bootstrap_icons %}

    <!-- Default template CSS -->
    <link rel="stylesheet" href="{% static 'main/css/main_base.css' %}">

    <!-- Child template style elements -->
    {% block styles %}
    {% endblock %}
</head>

<body>
<div class="wrapper">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SNF Scheduler</a>
            </div>
        </nav>
    </header>

    <div class="content-wrapper">
        <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'main:home' %}">
                            {% bs_icon 'house-door' %}
                            Home
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">
                            {% bs_icon 'people' %}
                            Admin Area
                        </a>
                    </li>
                    {% endif %}

                    <!-- API Section -->
                    <li class="nav-item">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>API</span>
                        </h6>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'scheduler:api-root' %}">
                            {% bs_icon 'box' %}
                            Browseable API
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authentication:tokens' %}">
                            {% bs_icon 'key' %}
                            API Tokens
                        </a>
                    </li>

                    <!-- Management Section -->
                    <li class="nav-item">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Management</span>
                        </h6>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:list_snfs' %}">
                            {% bs_icon 'clipboard-pulse' %}
                            SNF Manager
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:list_patients' %}">
                            {% bs_icon 'people' %}
                            Patient Manager
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Session</span>
                        </h6>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authentication:logout' %}">
                            {% bs_icon 'box-arrow-right' %}
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
            {% block content %}
            <h1>Main Content Area</h1>
            <p>Content in this block should be overridden in the child templates.</p>
            {% endblock %}
        </main>
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">&copy; 2024 Nathan Rasch</span>
        </div>
    </footer>
</div>

<!-- Bootstrap JS -->
{% bootstrap_javascript %}
{% block scripts %}
{% endblock %}
</body>
</html>

snf_scheduler/main/templates/main/edit_snf.html
{% load widget_tweaks %}
<div class="modal-body">
    <form method="post" id="editSNFForm" novalidate>
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Please correct the errors below.</p>
            </div>
        {% endif %}

        {{ form.non_field_errors }}  {# Errors not associated with a specific field #}

        <div class="row g-3">
            {% for field in form %}
                <div class="col-md-6 {% if field.errors %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="form-label {% if field.errors %}text-danger{% endif %}">{{ field.label }}</label></br>
                    {% if field.errors %}
                        {{ field|add_class:"form-control is-invalid" }}
                    {% else %}
                        {{ field|add_class:"form-control" }}
                    {% endif %}
                    {% if field.errors %}
                        <div class="invalid-feedback">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                    {% if field.help_text %}
                        <div id="{{ field.id_for_label }}Help" class="form-text">{{ field.help_text }}</div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </form>
</div>

snf_scheduler/main/templates/main/patient.html
{% extends "main/base.html" %}
{% load static %}
{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block title %}Patient Manager{% endblock %}

{% block styles %}
<link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.0/datatables.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <p class="h2"><span class="text-primary">Patient Manager</span></p>
    <p class="h4"><span class="text-primary">(Utilizing Django Views to Process AJAX Requests)</span></p>
    <div class="toast-container mt-2">
        <div id="patientToast" class="toast align-items-center text-white bg-secondary bg-gradient border-0 mt-5" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body" id="toastMessage">
                    Patient has been processed successfully.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <table id="patient-table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date of Birth</th>
                <th>Age</th>
                <th>Last Appointment</th>
                <th>Next Appointment</th>
                <th>Active</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- The initial table body is empty because data will be loaded via AJAX -->
        </tbody>
        <tfoot>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date of Birth</th>
                <th>Age</th>
                <th>Last Appointment</th>
                <th>Next Appointment</th>
                <th>Active</th>
                <th>Actions</th>
            </tr>
        </tfoot>
    </table>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary mt-3" id="loadAddPatientModalBtn">Add Patient</button>
    <button type="button" class="btn btn-secondary mt-3" id="refreshData">
        Refresh Data
    </button>

    <!-- Modal for Adding Patients -->
    <div id="addPatientModalContainer">
    </div>

    <!-- Modal for Editing Patients -->
    <div id="editPatientModalContainer">
    </div>


</div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.0/datatables.min.js"></script>
<script>
$(document).ready(function() {
    // DATATABLE INIT FOR PATIENT TABLE
    // Create global variable, so we can access in other scripts loaded further below
    window.patientTable = $('#patient-table').DataTable({
        ajax: {
            url: "{% url 'main:list_patients' %}",
            type: "GET",
            dataSrc: "data"
        },
        "paging": true,
        "ordering": true,
        "searching": true,
        "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
        "pageLength": 10,
        "columns": [
            { "data": "first_name" },
            { "data": "last_name" },
            { "data": "date_of_birth" },
            { "data": "age" },
            { "data": "date_of_last_appointment" },
            { "data": "date_of_next_appointment" },
            { "data": "active" },
            { "data": null } // Column to hold custom form actions (buttons, etc.)
        ],
        "columnDefs": [
            {
                // Define custom form actions
                "targets": -1, // Targets the last column
                "data": null,
                "defaultContent": "<button class='btn btn-sm btn-outline-primary edit-btn'>Edit</button> \
                &nbsp;&nbsp;<button class='btn btn-sm btn-outline-danger delete-btn'>Delete</button>"
            }
        ]
    });


    // REFRESH PATIENT DATATABLE
    $('#refreshData').on('click', function() {
        // Reload the patient table data
        window.patientTable.ajax.reload();
    });

});
</script>
<script>
    // Define any Django template tag values that need to be passed to the JavaScript files loaded later below
    var addPatientUrl = "{% url 'main:add_patient' %}";
    var editPatientUrl = "{% url 'main:edit_patient' 0 %}";
    var deletePatientUrl = "{% url 'main:delete_patient' %}";
    var patientID = 0;
    var csrfToken = "{{ csrf_token }}";

    console.log("addPatientUrl: " + addPatientUrl);
    console.log("editPatientUrl: " + editPatientUrl);
    console.log("deletePatientUrl: " + deletePatientUrl);
    console.log("csrfToken: " + csrfToken);
</script>
<script src="{% static 'main/js/add_patient.js' %}"></script>
<script src="{% static 'main/js/edit_patient.js' %}"></script>
{% endblock %}